services:
  ses:
    image: redis:7.0
    hostname: ses
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SSSDB;Integrated Security=true;TrustServerCertificate=True
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
  sss:
    image: redis:7.0
    hostname: sss
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SSSDB;Integrated Security=true;TrustServerCertificate=True
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin1234
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:
  redis-data:
  minio-data: